// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewYourPayments.EntityFramework;

#nullable disable

namespace ViewYourPayments.EntityFramework.Migrations
{
    [DbContext(typeof(ViewYourPaymentsDbContext))]
    partial class ViewYourPaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.BudgetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BudgetGroupDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContractCodePrefix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("ContractCodePrefix")
                        .IsUnique()
                        .HasFilter("[ContractCodePrefix] IS NOT NULL");

                    b.ToTable("BudgetGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetGroupDescription = "16-18 Traineeships",
                            ContractCodePrefix = "16TR",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BudgetGroupDescription = "16-19 Funding",
                            ContractCodePrefix = "16ED",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BudgetGroupDescription = "16-19 Funding",
                            ContractCodePrefix = "16LR",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BudgetGroupDescription = "16-19 Funding",
                            ContractCodePrefix = "NLG",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BudgetGroupDescription = "16-19 Funding",
                            ContractCodePrefix = "NMF",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BudgetGroupDescription = "16-19 Funding",
                            ContractCodePrefix = "SSF",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BudgetGroupDescription = "Advanced Learner Loans",
                            ContractCodePrefix = "ALLB",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BudgetGroupDescription = "Advanced Learner Loans",
                            ContractCodePrefix = "ALLC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BudgetGroupDescription = "Advanced Learner Loans",
                            ContractCodePrefix = "ALLF",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BudgetGroupDescription = "Advanced Learner Loans",
                            ContractCodePrefix = "CLP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BudgetGroupDescription = "Apprenticeship Grant for Employers",
                            ContractCodePrefix = "AGE",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BudgetGroupDescription = "Apprenticeship (Employer on App service) Levy",
                            ContractCodePrefix = "LEVY",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BudgetGroupDescription = "Apprenticeship (Employer on App service) Non-Levy",
                            ContractCodePrefix = "NLA",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "16AP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "16NL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "AAPP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "ANL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "APPS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BudgetGroupDescription = "European Social Fund",
                            ContractCodePrefix = "ESF",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSA",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSD",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSE",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSF",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSI",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCSV",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AEC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AECA",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AECL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AECT",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AELS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "AEO",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEBL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEBT",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEAL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEBA",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEBC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AEBR",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            BudgetGroupDescription = "Procured Adult Education Budget",
                            ContractCodePrefix = "AETL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            BudgetGroupDescription = "Procured Non-Levy Apprenticeships",
                            ContractCodePrefix = "ANAS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            BudgetGroupDescription = "Procured Non-Levy Apprenticeships",
                            ContractCodePrefix = "ANLP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            BudgetGroupDescription = "Procured Non-Levy Apprenticeships",
                            ContractCodePrefix = "YNAS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            BudgetGroupDescription = "Procured Non-Levy Apprenticeships",
                            ContractCodePrefix = "YNLP",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "AATO",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            BudgetGroupDescription = "Apprenticeships Carry-in",
                            ContractCodePrefix = "AAC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            BudgetGroupDescription = "National Careers Service",
                            ContractCodePrefix = "NCS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "ASC",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "ASTO",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "DL",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            BudgetGroupDescription = "Non-Procured Adult Education Budget",
                            ContractCodePrefix = "DLS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            BudgetGroupDescription = "Employer Ownership Pilot",
                            ContractCodePrefix = "EOP1",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            BudgetGroupDescription = "Offender Learning and Skills Strategy",
                            ContractCodePrefix = "OLAS",
                            CreatedOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            BudgetGroupDescription = "Non-Learning Grants",
                            ContractCodePrefix = "CCF",
                            CreatedOn = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.DataImportAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataImportAudits");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.DataImportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("ESFA");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("RequestedUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RunFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RunToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkipTokenNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("DataImportHistories");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BudgetGroup")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contract")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Establishment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstablishmentDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FundingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentLineDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentLineGroupDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentLineIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentSummaryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentLineIdentifier");

                    b.HasIndex("PaymentSummaryId");

                    b.HasIndex("Contract", "PaymentLineDescription", "PaymentLineGroupDescription", "LineAmount", "BudgetGroup");

                    b.ToTable("PaymentLines");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentLineStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BudgetGroup")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contract")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Establishment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstablishmentDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FundingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentLineDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentLineGroupDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentLineIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentSummaryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSummaryId");

                    b.ToTable("PaymentLinesStaging");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("DataImportHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentIdentifier")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ukprn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VendorIdentifier")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DataImportHistoryId");

                    b.HasIndex("PaymentIdentifier");

                    b.HasIndex("PaymentDate", "Ukprn", "PaymentTotal");

                    b.ToTable("PaymentSummaries");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummaryStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataImportHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentIdentifier")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ukprn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VendorIdentifier")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DataImportHistoryId");

                    b.ToTable("PaymentSummariesStaging");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentLine", b =>
                {
                    b.HasOne("ViewYourPayments.Core.Models.Payments.PaymentSummary", "PaymentSummary")
                        .WithMany("PaymentLine")
                        .HasForeignKey("PaymentSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentLineStaging", b =>
                {
                    b.HasOne("ViewYourPayments.Core.Models.Payments.PaymentSummaryStaging", "PaymentSummary")
                        .WithMany("PaymentLine")
                        .HasForeignKey("PaymentSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummary", b =>
                {
                    b.HasOne("ViewYourPayments.Core.Models.Payments.DataImportHistory", "DataImportHistory")
                        .WithMany("PaymentSummaryList")
                        .HasForeignKey("DataImportHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataImportHistory");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummaryStaging", b =>
                {
                    b.HasOne("ViewYourPayments.Core.Models.Payments.DataImportHistory", "DataImportHistory")
                        .WithMany("PaymentSummaryStagingList")
                        .HasForeignKey("DataImportHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataImportHistory");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.DataImportHistory", b =>
                {
                    b.Navigation("PaymentSummaryList");

                    b.Navigation("PaymentSummaryStagingList");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummary", b =>
                {
                    b.Navigation("PaymentLine");
                });

            modelBuilder.Entity("ViewYourPayments.Core.Models.Payments.PaymentSummaryStaging", b =>
                {
                    b.Navigation("PaymentLine");
                });
#pragma warning restore 612, 618
        }
    }
}
